from __future__ import annotations

import argparse
import csv
import json
import io
import shutil
import time
from threading import Event
from datetime import datetime
from pathlib import Path
from typing import Dict, Iterable, List, Tuple

PATH_OS_SIOU = r"/home/integracao/Arquivos/Siou/ImpOS/"

ACCEPTED_FIELDS_TRATAMENTOS = {
    "OPTO CLASS",
    "SÓ ANTIRRISCO",
    "OPTO GOLD VERDE",
    "OPTO GOLD DOURADO",
    "OPTO EXTRA CLEAN",
    "SUPER OPTO",
    "OPTO DIGITAL",
    "RETIRAR O TRATAMENTO",
    "REFAZER | GARANTIA",
    "OPTO IR BLOCK PRO",
}

ACCEPTED_FIELDS_MATERIAIS = {
    "ORGÂNICO 1.499",
    "ORGÂNICO 1.56",
    "ORGÂNICO 1.67",
    "ORGÂNICO 1.74",
    "POLICARBONATO",
    "TRIVEX",
    "OUTROS",
    "ORGÂNICO 1.60",
}

ACCEPTED_FIELDS_FABRICANTES = {
    "ESSILOR",
    "HOYA",
    "RODENSTOCK",
    "ZEISS",
    "Outros",
}  

ACCEPTED_FIELDS_TIPOS_DE_LENTES = {
    "VISÃO SIMPLES",
    "BIFOCAL",
    "MULTIFOCAL - CONVENCIONAL",
    "MULTIFOCAL - PROGRESSIVA",
    "OUTROS",
}

ACCEPTED_FIELDS_OBSERVACOES = {
    "Sem Observações",
    "Já tem antirrisco",
    "Somente interno",
    "Refazer",
    "garantia",
    "APENAS Retirada",
}


FIELD_MAP_SIOU: Dict[int, str] = {
	0: "os_laboratorio",
	1: "quantidade",
	2: "codigo_cliente",
	3: "esf_od",
	4: "cil_od",
	5: "eixo_od",
	6: "adicao_od",
	7: "esf_oe",
	8: "cil_oe",
	9: "eixo_oe",
	10: "adicao_oe",
	11: "prisma_od",
	12: "eixo_prisma_od",
	13: "prisma2_od",
	14: "eixo_pr2_od",
	15: "prisma_oe",
	16: "eixo_prisma_oe",
	17: "prisma2_oe",
	18: "eixo_pr2_oe",
	19: "dnp_l_od",
	20: "dnp_p_od",
	21: "dnp_l_oe",
	22: "dnp_p_oe",
	23: "shape_id",
	24: "diametro_padrao",
	25: "numero_caixa",
	26: "tipo_armacao",
	27: "dbl_ponte",
	28: "ponte_mais_aro",
	29: "dv_altura_armacao",
	30: "dm_diagonal_maior",
	31: "apup_od",
	32: "apup_oe",
	33: "apel_od",
	34: "apel_oe",
	35: "codigo_produto_od",
	36: "codigo_produto_oe",
	37: "codigo_barras_bloco_od",
	38: "codigo_barras_bloco_oe",
	39: "crib_od",
	40: "crib_oe",
	41: "observacoes",
	42: "referencia_pedido_cliente",
	43: "codigo_pedido_cliente",
	44: "sequencia_pedido",
	45: "impressora",
	46: "curva_base_od",
	47: "curva_base_oe",
	48: "raio_od",
	49: "raio_oe",
	50: "espessura_bloco_od",
	51: "espessura_bloco_oe",
	52: "curva_interna_od",
	53: "curva_interna_oe",
	54: "indice_refracao_od",
	55: "indice_refracao_oe",
	56: "altura_elipse_od",
	57: "altura_elipse_oe",
	58: "espessura_min_borda_od",
	59: "espessura_min_borda_oe",
	60: "espessura_min_centro_od",
	61: "espessura_min_centro_oe",
	62: "descentracao_horizontal_od",
	63: "descentracao_horizontal_oe",
	64: "diametro_od",
	65: "diametro_oe",
	66: "cod_trat_01",
	67: "cod_trat_02",
	68: "cod_trat_03",
	69: "cod_trat_04",
	70: "cod_trat_05",
	71: "abreviacao_nome_cliente_laser",
	72: "active_auto_calc",
	73: "codigo_opticlick",
	74: "dha_largura_armacao",
	75: "campo_75",
	76: "campo_76",
	77: "campo_77",
	78: "campo_78",
	79: "anamnese_ocupacao",
	80: "anamnese_hobby",
	81: "anamnese_necessidade_visual",
	82: "anamnese_horas_direcao",
	83: "anamnese_horas_tv",
	84: "anamnese_horas_computador",
	85: "anamnese_horas_leitura",
	86: "anamnese_nome_cliente_caneta",
	87: "id_empresa",
	88: "centro_custo",
	89: "finalidade_pedido",
	90: "engraving_01",
	91: "engraving_02",
	92: "engraving_03",
	93: "engraving_04",
	94: "lente_pronta_od",
	95: "lente_pronta_oe",
	96: "fwd",
	97: "nwd",
	98: "vmap",
	99: "material_bloco_od",
	100: "material_bloco_oe",
	101: "diametro_bloco_od",
	102: "diametro_bloco_oe",
	103: "nome_medico",
	104: "nome_vendedor",
	105: "data_entrega_combinada",
	106: "corrlen_od",
	107: "corrlen_oe",
	108: "ato_od",
	109: "ato_oe",
	110: "clage",
}

